version: "3.9"

services:
  realtime-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realtime-service
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8080
      - REALTIME_ENABLE_WEBSOCKET=true
      - REALTIME_ENABLE_WEBTRANSPORT=true
      - WEBTRANSPORT_SECRET=assessment-platform-secret
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
      - PASETO_PUBLIC_KEY=MCowBQYDK2VwAyEAMSnxVl9HDU/a8MTM7ZjVr4stDU0pgXo6IL68tdjxFk0=
    command: ["npm", "run", "start:realtime"]
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - gateway-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  gateway-network:
    external: true
    name: gateway-network
