version: "3.9"

services:
  user-db:   # renamed from db
    image: postgres:15
    container_name: userservice-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - userservice-data:/var/lib/postgresql/data
    networks:
      - pediafor-network

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: userservice
    restart: always
    depends_on:
      - user-db   # renamed
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
    networks:
      - pediafor-network

volumes:
  userservice-data:

networks:
  pediafor-network:
    driver: bridge
