services:
  user-service:
    volumes:
      - ./src:/usr/src/app/src          # Mount only source files
      - ./prisma:/usr/src/app/prisma    # Mount prisma schema
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install && npx prisma generate &&
             npx ts-node-dev --respawn --transpile-only src/server.ts"
    ports:
      - "4000:4000"
