version: "3.9"

services:
  user-service:
    volumes:
      - ./user-service:/usr/src/app          # Mount source code for live updates
      - /usr/src/app/node_modules            # Keep node_modules inside container
    command: >
      sh -c "npx prisma generate &&
             npx tsc --watch &
             node dist/server.js"
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"
