services:
  user-service:
    volumes:
      - ./src:/usr/src/app/src          # Mount only source files
      - ./prisma:/usr/src/app/prisma    # Mount prisma schema
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - /usr/src/app/node_modules       # Keep container node_modules
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npx prisma generate &&
             npx ts-node-dev --respawn --transpile-only src/server.ts"
    ports:
      - "3001:3000"
