version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pediafor-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: pediafor
      POSTGRES_PASSWORD: pediafor
      POSTGRES_DB: pediafor
    ports:
      - "5432:5432"
    volumes:
      # Persistent database storage
      - pediafor_db_data:/var/lib/postgresql/data

      # Mount db folder into container so SQL files can be run easily
      - ./:/app/db

    # Optional but recommended: healthcheck ensures DB is ready before Prisma connects
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pediafor -d pediafor"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pediafor_db_data:
